# BlockRacing 游戏设置
# 该配置文件仅用于服务器重启后保留设置数据
# 服务器关闭时将自动保存本局游戏的设置到该文件
# 如果服务器已启动，请前往游戏中的设置界面进行设置，不要在这里调整

# 语言
lang: zh_cn

# 除去easy-block以外的四种额外方块库设置
medium-block: false
hard-block: false
dyed-block: false
end-block: false

# 一局游戏需要收集的方块总数
block-amount: 50

# 游戏模式：
# normal - 普通模式：两个队伍需要收集的方块及顺序完全随机，收集方块会将一组该方块给到对方的队伍箱子里
# racing - 竞速模式：两个队伍需要收集的方块及顺序将完全相同，且收集方块将不会给予一组方块到对方队伍箱子里
game-mode: normal

# 极速模式：
# 开启极速模式后，开局时将会给予玩家部分道具和效果，且获得方块时加3分，以加快游戏进度
# 物品：精准采集铁镐、熟牛排、损坏的鞘翅、经验修补附魔书
# 效果：急迫V
speed-mode: false

# 如果你不知道这是什么，不要动它
config-version: 3.0