name: BlockRacing
version: '1.0'
main: top.lqsnow.blockracing.Main
api-version: 1.19
authors: [ LQ_Snow ]
description: The first team to collect the required blocks wins
commands:
  tp:
    usage: "/tp <Teammate>"
    description: "TP to teammate."
  locate:
    usage: "/locate <Structure | Biome>"
    description: "Locate structure or biome."
  restartgame:
    usage: "/restartgame"
    description: "Restart the game."