name: BlockRacing
version: 3.2
main: top.lqsnow.blockracing.Main
api-version: 1.21
authors: [ LQ_Snow ]
description: The first team to collect the required blocks wins
commands:
  tp:
    usage: "/tp <Teammate>"
    description: "TP to teammate."
  locatestructure:
    usage: "/locate <Structure>"
    description: "Locate structure."
  locatebiome:
    usage: "/locate <Biome>"
    description: "Locate biome."
  restartgame:
    usage: "/restartgame"
    description: "Restart the game."
  debug:
    usage: "/debug"
    description: "Debug."
    permission: op
  menu:
    usage: "/menu"
    description: "Open the menu."
  waypoint:
    usage: "/waypoint"
    description: "Run waypoint commands."
  block:
    usage: "/block <team> <number>"
    description: "Query block."